[package]
name = "wasm-runtime-benchmarks"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
wat = "1.256.0"
wasmtime = { version = "45.0.3", default-features = true, features = ["winch"] }
criterion = "0.8.2"

[[bench]]
name = "table-grow"
path = "benches/wasmtime/table_grow.rs"
harness = false
